[package]
name = "binge"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tabled = "0.18"
